package unipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import unipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.07 13:17:40 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KayttajatTest {



  // Generated by ComTest BEGIN
  /** testLisaa30 */
  @Test
  public void testLisaa30() {    // Kayttajat: 30
    Kayttajat kayttajat = new Kayttajat(); 
    Kayttaja nea = new Kayttaja("Nea"), ansku = new Kayttaja("Ansku"); 
    assertEquals("From: Kayttajat line: 33", 0, kayttajat.getLkm()); 
    kayttajat.lisaa(nea); assertEquals("From: Kayttajat line: 34", 1, kayttajat.getLkm()); 
    kayttajat.lisaa(ansku); assertEquals("From: Kayttajat line: 35", 2, kayttajat.getLkm()); 
    kayttajat.lisaa(nea); assertEquals("From: Kayttajat line: 36", 3, kayttajat.getLkm()); 
    assertEquals("From: Kayttajat line: 37", nea, kayttajat.anna(0)); 
    assertEquals("From: Kayttajat line: 38", ansku, kayttajat.anna(1)); 
    assertEquals("From: Kayttajat line: 39", nea, kayttajat.anna(2)); 
    assertEquals("From: Kayttajat line: 40", false, kayttajat.anna(1) == nea); 
    assertEquals("From: Kayttajat line: 41", true, kayttajat.anna(1) == ansku); 
    try {
    assertEquals("From: Kayttajat line: 42", nea, kayttajat.anna(3)); 
    fail("Kayttajat: 42 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    kayttajat.lisaa(nea); assertEquals("From: Kayttajat line: 43", 4, kayttajat.getLkm()); 
    kayttajat.lisaa(nea); assertEquals("From: Kayttajat line: 44", 5, kayttajat.getLkm()); 
    kayttajat.lisaa(nea); assertEquals("From: Kayttajat line: 45", 6, kayttajat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testKasvataTaulukkoa59 */
  @Test
  public void testKasvataTaulukkoa59() {    // Kayttajat: 59
    Kayttajat kayttajat = new Kayttajat(); 
    Kayttaja nea = new Kayttaja("Nea"), ansku = new Kayttaja("Ansku"), liisa = new Kayttaja("Liisa"); 
    kayttajat.lisaa(nea); assertEquals("From: Kayttajat line: 62", 1, kayttajat.getLkm()); 
    kayttajat.lisaa(ansku); assertEquals("From: Kayttajat line: 63", 2, kayttajat.getLkm()); 
    kayttajat.lisaa(liisa); assertEquals("From: Kayttajat line: 64", 3, kayttajat.getLkm()); 
    kayttajat.lisaa(nea); assertEquals("From: Kayttajat line: 65", 4, kayttajat.getLkm()); 
    kayttajat.lisaa(ansku); assertEquals("From: Kayttajat line: 66", 5, kayttajat.getLkm()); 
  } // Generated by ComTest END
}