package unipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import unipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.06 13:25:25 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KayttajaTest {



  // Generated by ComTest BEGIN
  /** testGetNimi28 */
  @Test
  public void testGetNimi28() {    // Kayttaja: 28
    Kayttaja nea = new Kayttaja("Nea"); 
    nea.taytaNeaTiedoilla(); 
    { String _l_=nea.getNimi(),_r_="Nea"; if ( !_l_.matches(_r_) ) fail("From: Kayttaja line: 31" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi61 */
  @Test
  public void testRekisteroi61() {    // Kayttaja: 61
    Kayttaja nea = new Kayttaja("Nea"); 
    assertEquals("From: Kayttaja line: 63", 1, nea.getKayttajaId()); 
    nea.rekisteroi(); 
    Kayttaja ansku = new Kayttaja("Ansku"); 
    ansku.rekisteroi(); 
    int n1 = nea.getKayttajaId(); 
    int n2 = ansku.getKayttajaId(); 
    assertEquals("From: Kayttaja line: 69", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKayttajaId83 */
  @Test
  public void testGetKayttajaId83() {    // Kayttaja: 83
    Kayttaja nea = new Kayttaja("Nea"); 
    nea.taytaNeaTiedoilla(); 
    assertEquals("From: Kayttaja line: 86", 1, nea.getKayttajaId()); 
  } // Generated by ComTest END
}