package unipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import unipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.06 13:19:51 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KayttajatTest {



  // Generated by ComTest BEGIN
  /** testLisaa32 
 * @throws SailoException jos lisääminen ei toimi*/
  @Test
  public void testLisaa32() throws SailoException {    // Kayttajat: 32
    Kayttajat kayttajat = new Kayttajat(); 
    Kayttaja nea = new Kayttaja("Nea"), ansku = new Kayttaja("Ansku"); 
    assertEquals("From: Kayttajat line: 35", 3, kayttajat.getLkm()); 
    kayttajat.lisaa(nea); assertEquals("From: Kayttajat line: 36", 1, kayttajat.getLkm()); 
    kayttajat.lisaa(ansku); assertEquals("From: Kayttajat line: 37", 2, kayttajat.getLkm()); 
    kayttajat.lisaa(nea); assertEquals("From: Kayttajat line: 38", 3, kayttajat.getLkm()); 
    assertEquals("From: Kayttajat line: 39", nea, kayttajat.anna(0)); 
    assertEquals("From: Kayttajat line: 40", ansku, kayttajat.anna(1)); 
    assertEquals("From: Kayttajat line: 41", nea, kayttajat.anna(2)); 
    assertEquals("From: Kayttajat line: 42", false, kayttajat.anna(1) == nea); 
    assertEquals("From: Kayttajat line: 43", true, kayttajat.anna(1) == ansku); 
    try {
    assertEquals("From: Kayttajat line: 44", nea, kayttajat.anna(3)); 
    fail("Kayttajat: 44 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    kayttajat.lisaa(nea); assertEquals("From: Kayttajat line: 45", 4, kayttajat.getLkm()); 
    kayttajat.lisaa(nea); assertEquals("From: Kayttajat line: 46", 5, kayttajat.getLkm()); 
    try {
    kayttajat.lisaa(nea); 
    fail("Kayttajat: 47 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}