package unipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static unipaivakirja.KloTarkistus.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.06 15:03:10 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KloTarkistusTest {



  // Generated by ComTest BEGIN
  /** testKellonajanTarkistus19 */
  @Test
  public void testKellonajanTarkistus19() {    // KloTarkistus: 19
    assertEquals("From: KloTarkistus line: 20", null, kellonajanTarkistus("15:05")); 
    assertEquals("From: KloTarkistus line: 21", null, kellonajanTarkistus("09:00")); 
    assertEquals("From: KloTarkistus line: 22", null, kellonajanTarkistus("23:46")); 
    assertEquals("From: KloTarkistus line: 23", "Tunnit liian isot tai pienet", kellonajanTarkistus("26:40")); 
    assertEquals("From: KloTarkistus line: 24", "Minuutit liian isot tai pienet", kellonajanTarkistus("00:67")); 
    assertEquals("From: KloTarkistus line: 25", null, kellonajanTarkistus("6:30")); 
    assertEquals("From: KloTarkistus line: 26", "Kaksoispiste puuttuu", kellonajanTarkistus("440")); 
    assertEquals("From: KloTarkistus line: 27", "Kaksoispiste puuttuu", kellonajanTarkistus("9")); 
    assertEquals("From: KloTarkistus line: 28", "Minuuteissa liian vähän merkkejä", kellonajanTarkistus("3:2")); 
    assertEquals("From: KloTarkistus line: 29", "Kellonajassa virheellisiä merkkejä", kellonajanTarkistus("oo:l0")); 
    assertEquals("From: KloTarkistus line: 30", "Tunnit liian isot tai pienet", kellonajanTarkistus("-4:30")); 
  } // Generated by ComTest END
}