package unipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import unipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.06 13:22:53 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class MerkinnatTest {


  // Generated by ComTest BEGIN
  /** 
   * testLisaa35 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa35() throws SailoException {    // Merkinnat: 35
    Merkinnat merkinnat = new Merkinnat(); 
    Merkinta pvm1 = new Merkinta(), pvm2 = new Merkinta(); 
    assertEquals("From: Merkinnat line: 39", 0, merkinnat.getLkm()); 
    merkinnat.lisaa(pvm1); assertEquals("From: Merkinnat line: 40", 1, merkinnat.getLkm()); 
    merkinnat.lisaa(pvm2); assertEquals("From: Merkinnat line: 41", 2, merkinnat.getLkm()); 
    merkinnat.lisaa(pvm1); assertEquals("From: Merkinnat line: 42", 3, merkinnat.getLkm()); 
    assertEquals("From: Merkinnat line: 43", pvm1, merkinnat.anna(0)); 
    assertEquals("From: Merkinnat line: 44", pvm2, merkinnat.anna(1)); 
    assertEquals("From: Merkinnat line: 45", pvm1, merkinnat.anna(2)); 
    assertEquals("From: Merkinnat line: 46", false, merkinnat.anna(1) == pvm1); 
    assertEquals("From: Merkinnat line: 47", true, merkinnat.anna(1) == pvm2); 
    try {
    assertEquals("From: Merkinnat line: 48", pvm1, merkinnat.anna(3)); 
    fail("Merkinnat: 48 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    merkinnat.lisaa(pvm1); assertEquals("From: Merkinnat line: 49", 4, merkinnat.getLkm()); 
    merkinnat.lisaa(pvm1); assertEquals("From: Merkinnat line: 50", 5, merkinnat.getLkm()); 
    merkinnat.lisaa(pvm1); assertEquals("From: Merkinnat line: 51", 6, merkinnat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testKasvataTaulukkoa65 
 * @throws SailoException jos lisääminen ei onnistu*/
  @Test
  public void testKasvataTaulukkoa65() throws SailoException {    // Merkinnat: 65
    Merkinnat merkinnat = new Merkinnat(); 
    Merkinta alkiot[] = new Merkinta[3]; 
    Merkinta pvm1 = new Merkinta(), pvm2 = new Merkinta(), pvm3 = new Merkinta(); 
    merkinnat.lisaa(pvm1); assertEquals("From: Merkinnat line: 69", 1, merkinnat.getLkm()); 
    merkinnat.lisaa(pvm2); assertEquals("From: Merkinnat line: 70", 2, merkinnat.getLkm()); 
    merkinnat.lisaa(pvm3); assertEquals("From: Merkinnat line: 71", 3, merkinnat.getLkm()); 
    assertEquals("From: Merkinnat line: 72", 3, alkiot.length); 
    merkinnat.lisaa(pvm1); assertEquals("From: Merkinnat line: 73", 4, merkinnat.getLkm()); 
    merkinnat.lisaa(pvm3); assertEquals("From: Merkinnat line: 74", 5, merkinnat.getLkm()); 
    assertEquals("From: Merkinnat line: 75", 13, alkiot.length); 
  } // Generated by ComTest END
}