package unipaivakirja.test;
// Generated by ComTest BEGIN
import java.text.SimpleDateFormat;
import java.util.Date;
import static org.junit.Assert.*;
import org.junit.*;
import unipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.07 13:21:35 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class MerkintaTest {



  // Generated by ComTest BEGIN
  /** testGetPvm52 */
  @Test
  public void testGetPvm52() {    // Merkinta: 52
    Merkinta pvm1 = new Merkinta(); 
    pvm1.taytaM1Tiedoilla(); 
    assertEquals("From: Merkinta line: 55", "12.3.2022", pvm1.getPvm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testMerkinnanLisays138 */
  @Test
  public void testMerkinnanLisays138() {    // Merkinta: 138
    Merkinta pvm1 = new Merkinta(); 
    assertEquals("From: Merkinta line: 140", 0, pvm1.getMerkintaid()); 
    pvm1.merkinnanLisays(); 
    Merkinta pvm2 = new Merkinta(); 
    pvm2.merkinnanLisays(); 
    int n1 = pvm1.getMerkintaid(); 
    int n2 = pvm2.getMerkintaid(); 
    assertEquals("From: Merkinta line: 146", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetMerkintaid168 */
  @Test
  public void testGetMerkintaid168() {    // Merkinta: 168
    Merkinta pvm1 = new Merkinta(); 
    pvm1.merkinnanLisays(); 
    assertEquals("From: Merkinta line: 171", 1, pvm1.getMerkintaid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLaskeUnenmaara194 */
  @Test
  public void testLaskeUnenmaara194() {    // Merkinta: 194
    Merkinta merkinta = new Merkinta("21:00", "5:30"); 
    SimpleDateFormat unenmaara = new SimpleDateFormat("HH:mm"); 
    try {
    unenmaara.parse(merkinta.getNukkumaanKlo()); 
    unenmaara.parse(merkinta.getHeratysKlo()); 
    assertEquals("From: Merkinta line: 202", "15 h 30 min", merkinta.laskeUnenmaara()); 
    Merkinta merkinta2 = new Merkinta("1:00", "9:15"); 
    unenmaara = new SimpleDateFormat("HH:mm"); 
    unenmaara.parse(merkinta2.getNukkumaanKlo()); 
    unenmaara.parse(merkinta2.getHeratysKlo()); 
    assertEquals("From: Merkinta line: 207", "8 h 15 min", merkinta2.laskeUnenmaara()); 
    } catch(Exception e) {
    assertEquals("From: Merkinta line: 209", 0, 1); 
    }
  } // Generated by ComTest END
}