package unipaivakirja.test;
// Generated by ComTest BEGIN
import java.text.SimpleDateFormat;
import java.util.Date;
import static org.junit.Assert.*;
import org.junit.*;
import unipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.20 14:35:36 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class MerkintaTest {



  // Generated by ComTest BEGIN
  /** testGetPvm62 */
  @Test
  public void testGetPvm62() {    // Merkinta: 62
    Merkinta pvm1 = new Merkinta(); 
    pvm1.taytaM1Tiedoilla(); 
    assertEquals("From: Merkinta line: 65", "12.3.2022", pvm1.getPvm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testMerkinnanLisays149 */
  @Test
  public void testMerkinnanLisays149() {    // Merkinta: 149
    Merkinta pvm1 = new Merkinta(); 
    assertEquals("From: Merkinta line: 151", 0, pvm1.getMerkintaid()); 
    pvm1.merkinnanLisays(); 
    Merkinta pvm2 = new Merkinta(); 
    pvm2.merkinnanLisays(); 
    int n1 = pvm1.getMerkintaid(); 
    int n2 = pvm2.getMerkintaid(); 
    assertEquals("From: Merkinta line: 157", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetMerkintaid179 */
  @Test
  public void testGetMerkintaid179() {    // Merkinta: 179
    Merkinta pvm1 = new Merkinta(); 
    pvm1.merkinnanLisays(); 
    assertEquals("From: Merkinta line: 182", 1, pvm1.getMerkintaid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse210 */
  @Test
  public void testParse210() {    // Merkinta: 210
    Merkinta merkinta = new Merkinta(3); 
    merkinta.parse("3|5|12.3.2015"); 
    assertEquals("From: Merkinta line: 213", 5, merkinta.getMerkintaid()); 
    assertEquals("From: Merkinta line: 214", true, merkinta.toString().startsWith("3|5|12.3.2015|"));  // on enemmäkin kuin 3 kenttää, siksi loppu | 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString233 */
  @Test
  public void testToString233() {    // Merkinta: 233
    Merkinta merkinta = new Merkinta(); 
    merkinta.parse("3|5|12.3.2015"); 
    assertEquals("From: Merkinta line: 236", true, merkinta.toString().startsWith("3|5|12.3.2015|"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLaskeUnenmaara268 */
  @Test
  public void testLaskeUnenmaara268() {    // Merkinta: 268
    Merkinta merkinta = new Merkinta("21:00", "5:30"); 
    SimpleDateFormat unenmaara = new SimpleDateFormat("HH:mm"); 
    try {
    unenmaara.parse(merkinta.getNukkumaanKlo()); 
    unenmaara.parse(merkinta.getHeratysKlo()); 
    assertEquals("From: Merkinta line: 276", "8 h 30 min", merkinta.laskeUnenmaara()); 
    Merkinta merkinta2 = new Merkinta("1:00", "9:15"); 
    unenmaara = new SimpleDateFormat("HH:mm"); 
    unenmaara.parse(merkinta2.getNukkumaanKlo()); 
    unenmaara.parse(merkinta2.getHeratysKlo()); 
    assertEquals("From: Merkinta line: 281", "8 h 15 min", merkinta2.laskeUnenmaara()); 
    } catch(Exception e) {
    assertEquals("From: Merkinta line: 283", 0, 1); 
    }
  } // Generated by ComTest END
}