package unipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import unipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.05.11 09:59:28 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class MerkintaTest {



  // Generated by ComTest BEGIN
  /** testGetPvm60 */
  @Test
  public void testGetPvm60() {    // Merkinta: 60
    Merkinta pvm1 = new Merkinta(); 
    pvm1.taytaM1Tiedoilla(); 
    assertEquals("From: Merkinta line: 63", "12.3.2022", pvm1.getPvm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testMerkinnanLisays154 */
  @Test
  public void testMerkinnanLisays154() {    // Merkinta: 154
    Merkinta pvm1 = new Merkinta(); 
    assertEquals("From: Merkinta line: 156", 0, pvm1.getMerkintaid()); 
    pvm1.merkinnanLisays(); 
    Merkinta pvm2 = new Merkinta(); 
    pvm2.merkinnanLisays(); 
    int n1 = pvm1.getMerkintaid(); 
    int n2 = pvm2.getMerkintaid(); 
    assertEquals("From: Merkinta line: 162", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetMerkintaid184 */
  @Test
  public void testGetMerkintaid184() {    // Merkinta: 184
    Merkinta pvm1 = new Merkinta(); 
    pvm1.merkinnanLisays(); 
    assertEquals("From: Merkinta line: 187", 1, pvm1.getMerkintaid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse215 */
  @Test
  public void testParse215() {    // Merkinta: 215
    Merkinta merkinta = new Merkinta(3); 
    merkinta.parse("3|5|12.3.2015"); 
    assertEquals("From: Merkinta line: 218", 5, merkinta.getMerkintaid()); 
    assertEquals("From: Merkinta line: 219", true, merkinta.toString().startsWith("3|5|12.3.2015|"));  // on enemmäkin kuin 3 kenttää, siksi loppu | 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString240 */
  @Test
  public void testToString240() {    // Merkinta: 240
    Merkinta merkinta = new Merkinta(); 
    merkinta.parse("3|5|12.3.2015"); 
    assertEquals("From: Merkinta line: 243", true, merkinta.toString().startsWith("3|5|12.3.2015|"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLaskeUnenmaara278 */
  @Test
  public void testLaskeUnenmaara278() {    // Merkinta: 278
    Merkinta m1 = new Merkinta("21:20", "7:15"); 
    Merkinta m2 = new Merkinta("1:00", "10:45"); 
    Merkinta m3 = new Merkinta("22:00", "2:00"); 
    Merkinta m4 = new Merkinta("5:10", "09:55"); 
    Merkinta m5 = new Merkinta("21:30", "6:30"); 
    Merkinta m6 = new Merkinta("22:15", "8:15"); 
    Merkinta m7 = new Merkinta("22:00", "7:00"); 
    assertEquals("From: Merkinta line: 286", "9 h 55 min", m1.laskeUnenmaara("21:20", "07:15")); 
    assertEquals("From: Merkinta line: 287", "9 h 45 min", m2.laskeUnenmaara("1:00", "10:45")); 
    assertEquals("From: Merkinta line: 288", "4 h 0 min", m3.laskeUnenmaara("22:00", "2:00")); 
    assertEquals("From: Merkinta line: 289", "4 h 45 min", m4.laskeUnenmaara("5:10", "09:55")); 
    assertEquals("From: Merkinta line: 290", "9 h 0 min", m5.laskeUnenmaara("21:30", "6:30")); 
    assertEquals("From: Merkinta line: 291", "10 h 0 min", m6.laskeUnenmaara("22:15", "8:15")); 
    assertEquals("From: Merkinta line: 292", "9 h 0 min", m7.laskeUnenmaara("22:00", "7:00")); 
  } // Generated by ComTest END
}