package unipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import unipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.07 10:19:22 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class UnenlaatuListaTest {


  // Generated by ComTest BEGIN
  /** testGetLkm70 */
  @Test
  public void testGetLkm70() {    // UnenlaatuLista: 70
    UnenlaatuLista alkiot = new UnenlaatuLista(); 
    alkiot.lisaa(new Unenlaatu("erittäin hyvä")); 
    alkiot.lisaa(new Unenlaatu("hyvä")); 
    alkiot.lisaa(new Unenlaatu("kohtalainen")); 
    alkiot.lisaa(new Unenlaatu("huono")); 
    alkiot.lisaa(new Unenlaatu("erittäin huono")); 
    assertEquals("From: UnenlaatuLista line: 77", 5, alkiot.getLkm()); 
  } // Generated by ComTest END
}