package unipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import unipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.07 13:15:10 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class UnipaivakirjaTest {


  // Generated by ComTest BEGIN
  /** testLisaa40 */
  @Test
  public void testLisaa40() {    // Unipaivakirja: 40
    Unipaivakirja unipaivakirja = new Unipaivakirja(); 
    Kayttaja nea = new Kayttaja("Nea"), ansku = new Kayttaja("Ansku"); 
    nea.rekisteroi(); ansku.rekisteroi(); 
    assertEquals("From: Unipaivakirja line: 44", 0, unipaivakirja.getKayttajia()); 
    unipaivakirja.lisaa(nea); assertEquals("From: Unipaivakirja line: 45", 1, unipaivakirja.getKayttajia()); 
    unipaivakirja.lisaa(ansku); assertEquals("From: Unipaivakirja line: 46", 2, unipaivakirja.getKayttajia()); 
    unipaivakirja.lisaa(nea); assertEquals("From: Unipaivakirja line: 47", 3, unipaivakirja.getKayttajia()); 
    assertEquals("From: Unipaivakirja line: 48", 3, unipaivakirja.getKayttajia()); 
    assertEquals("From: Unipaivakirja line: 49", nea, unipaivakirja.annaKayttaja(0)); 
    assertEquals("From: Unipaivakirja line: 50", ansku, unipaivakirja.annaKayttaja(1)); 
    assertEquals("From: Unipaivakirja line: 51", nea, unipaivakirja.annaKayttaja(2)); 
    try {
    assertEquals("From: Unipaivakirja line: 52", nea, unipaivakirja.annaKayttaja(3)); 
    fail("Unipaivakirja: 52 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    unipaivakirja.lisaa(nea); assertEquals("From: Unipaivakirja line: 53", 4, unipaivakirja.getKayttajia()); 
    unipaivakirja.lisaa(nea); assertEquals("From: Unipaivakirja line: 54", 5, unipaivakirja.getKayttajia()); 
    unipaivakirja.lisaa(nea); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaKayttaja69 */
  @Test
  public void testAnnaKayttaja69() {    // Unipaivakirja: 69
    Unipaivakirja unipaivakirja = new Unipaivakirja(); 
    Kayttaja nea = new Kayttaja("Nea"), ansku = new Kayttaja("Ansku"); 
    nea.rekisteroi(); 
    nea.rekisteroi(); 
    unipaivakirja.lisaa(nea); 
    unipaivakirja.lisaa(ansku); 
    assertEquals("From: Unipaivakirja line: 76", nea, unipaivakirja.annaKayttaja(0)); 
    assertEquals("From: Unipaivakirja line: 77", ansku, unipaivakirja.annaKayttaja(1)); 
    try {
    unipaivakirja.annaKayttaja(5); 
    fail("Unipaivakirja: 78 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}