package unipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import unipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.05.04 17:12:21 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class UnipaivakirjaTest {



  // Generated by ComTest BEGIN
  /** testLisaa33 */
  @Test
  public void testLisaa33() {    // Unipaivakirja: 33
    Unipaivakirja unipaivakirja = new Unipaivakirja(); 
    Kayttaja nea = new Kayttaja("Nea"), ansku = new Kayttaja("Ansku"); 
    nea.rekisteroi(); ansku.rekisteroi(); 
    assertEquals("From: Unipaivakirja line: 37", 0, unipaivakirja.getKayttajia()); 
    unipaivakirja.lisaa(nea); assertEquals("From: Unipaivakirja line: 38", 1, unipaivakirja.getKayttajia()); 
    unipaivakirja.lisaa(ansku); assertEquals("From: Unipaivakirja line: 39", 2, unipaivakirja.getKayttajia()); 
    unipaivakirja.lisaa(nea); assertEquals("From: Unipaivakirja line: 40", 3, unipaivakirja.getKayttajia()); 
    assertEquals("From: Unipaivakirja line: 41", 3, unipaivakirja.getKayttajia()); 
    assertEquals("From: Unipaivakirja line: 42", nea, unipaivakirja.annaKayttaja(0)); 
    assertEquals("From: Unipaivakirja line: 43", ansku, unipaivakirja.annaKayttaja(1)); 
    assertEquals("From: Unipaivakirja line: 44", nea, unipaivakirja.annaKayttaja(2)); 
    try {
    assertEquals("From: Unipaivakirja line: 45", nea, unipaivakirja.annaKayttaja(3)); 
    fail("Unipaivakirja: 45 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    unipaivakirja.lisaa(nea); assertEquals("From: Unipaivakirja line: 46", 4, unipaivakirja.getKayttajia()); 
    unipaivakirja.lisaa(nea); assertEquals("From: Unipaivakirja line: 47", 5, unipaivakirja.getKayttajia()); 
    unipaivakirja.lisaa(nea); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaKayttaja62 */
  @Test
  public void testAnnaKayttaja62() {    // Unipaivakirja: 62
    Unipaivakirja unipaivakirja = new Unipaivakirja(); 
    Kayttaja nea = new Kayttaja("Nea"), ansku = new Kayttaja("Ansku"); 
    nea.rekisteroi(); 
    nea.rekisteroi(); 
    unipaivakirja.lisaa(nea); 
    unipaivakirja.lisaa(ansku); 
    assertEquals("From: Unipaivakirja line: 69", nea, unipaivakirja.annaKayttaja(0)); 
    assertEquals("From: Unipaivakirja line: 70", ansku, unipaivakirja.annaKayttaja(1)); 
    try {
    unipaivakirja.annaKayttaja(5); 
    fail("Unipaivakirja: 71 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}