package unipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import unipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.07 10:29:04 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class VireystilaListaTest {


  // Generated by ComTest BEGIN
  /** testGetLkm65 */
  @Test
  public void testGetLkm65() {    // VireystilaLista: 65
    VireystilaLista alkiot = new VireystilaLista(); 
    alkiot.lisaa(new Vireystila("erittäin energinen")); 
    alkiot.lisaa(new Vireystila("pirteä")); 
    alkiot.lisaa(new Vireystila("ihan jees")); 
    alkiot.lisaa(new Vireystila("väsynyt")); 
    alkiot.lisaa(new Vireystila("erittäin väsynyt")); 
    assertEquals("From: VireystilaLista line: 72", 5, alkiot.getLkm()); 
  } // Generated by ComTest END
}