package test.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import test.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.05.12 11:20:33 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AllTestsTest { //
}